mentionIT/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mentionIT.Data;
using mentionIT.Models;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using System.IO;



namespace mentionIT.Controllers
{
    public class MealsController : Controller
    {
        private readonly mentionITContext _context;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public MealsController(mentionITContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            WebHostEnvironment = webHostEnvironment;
        }
        public IActionResult AccessDenied()
        {
            return View();
        }
        // GET: Meals
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Meal.ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Index(string mealSearch)
        {
            ViewData["Getmeals"] = mealSearch;
            var mealquery = from x in _context.Meal select x;

            if (!String.IsNullOrEmpty(mealSearch))
            {
                mealquery = mealquery.Where(x => x.Name.Contains(mealSearch));
            }
            //var meal = await mealquery.AsNoTracking().ToListAsync();
            return View(await mealquery.OrderBy(o => Guid.NewGuid()).AsNoTracking().ToListAsync());
        }
        // GET: Meals/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id, bool? changeLikes)
        {           
            if (id == null)
            {
                return NotFound();
            }
            var meal = await _context.Meal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meal == null)
            {
                return NotFound();
            }

            if (changeLikes == true)
            {
                
                string likeCookieName = Request.Cookies["ckiLikes"];
                if (!string.IsNullOrEmpty(likeCookieName))
                {
                    List<LikesUserLink> tempLst = _context.LikesUserLink.ToList<LikesUserLink>();
                    bool canLike = true;

                    for (int i = 0; i < tempLst.Count; i++)
                    {
                        if (tempLst[i].MealId==meal.Id&&tempLst[i].Liked==true&&tempLst[i].Name==likeCookieName)
                        {
                            canLike = false;
                            break;
                        }
                    }
                    if (canLike == true)
                    {
                        meal.Likes += 1;
                        _context.Update(meal);
                        int temp = tempLst.Count<LikesUserLink>();
                        LikesUserLink newRecord = new LikesUserLink { Id = default, Name = likeCookieName, Liked = true, MealId = meal.Id };
                        _context.Add(newRecord);
                    }
                }
                await _context.SaveChangesAsync();
            }
            return View(meal);
        }

        // GET: Meals/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult ImageAdd()
        {

            return View();
        }
        [HttpPost(Name = "Comments")]
        [Authorize]
        //[ValidateAntiForgeryToken]
        
        private bool HasImageExtension(string source)
        {
            if (source == null) { return false; }
            return (
                source.EndsWith(".png") ||
                source.EndsWith(".PNG") ||
                source.EndsWith(".jpeg") ||
                source.EndsWith(".JPEG") ||
                source.EndsWith(".gif") ||
                source.EndsWith(".GIF") ||
                source.EndsWith(".jpg") ||
                source.EndsWith(".JPG"));
        }
        [HttpPost(Name = "Comments")]
        [Authorize]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment([Bind("Message")] MealComment mealComment, int mealId)
        {
            // Find the meal with Id
            Meal meal = await _context.Meal.FindAsync(mealId);
            //Validate the model which have the comment
            if (ModelState.IsValid)
            {
                mealComment.Created = DateTime.Now;
                mealComment.Meal = meal;
                meal.Comments += mealComment.Message + "\n";
                _context.Add(mealComment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = meal.Id });

            }
            //Add the meal to the mealcomment
            //Save the comment 
            //redirect to details 


            return View(meal);
        }
        [HttpPost]
        public IActionResult ImageAdd(MealViewModel vm)
        {
            string stringFileName = UploadFile(vm);
            if (stringFileName == null)
            {
                
                return View("ImageAdd");
            }
            else
            {
                var meal = new Meal
                {

                    Id = vm.Id,
                    Name = vm.Name,
                    Cuisine = vm.Cuisine,
                    Likes = vm.Likes,
                    Comments = vm.Comments,
                    YLink = vm.YLink,
                    MealImage = stringFileName,
                    AuthorName = vm.AuthorName,
                    Description = vm.Description,
                    RecipeSteps = vm.RecipeSteps
                };
                _context.Meal.Add(meal);
                _context.SaveChanges();
                return RedirectToAction("Details", new { id = meal.Id });
            }
            
        }

        private string UploadFile(MealViewModel vm)
        {
            string fileName = null;
            if (vm.MealImage != null)
            {   

                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "ImageForMeals");
                fileName = Guid.NewGuid().ToString() + "-" + vm.MealImage.FileName;
                bool compareExtension = HasImageExtension(fileName) /*stringFileName.ToString().Substring(stringFileName.Length -4).ToUpper()*/;
                if (compareExtension == true)
                {
                    string filePath = Path.Combine(uploadDir, fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        vm.MealImage.CopyTo(fileStream);

                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid Extention File");
                    return null;
                }


            }
            {
                ModelState.AddModelError(string.Empty, "Please Enter File");
            }
            return fileName;
        }
        // POST: Meals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Cuisine,Likes,Comments,YLink")] Meal meal )
        {
            if (ModelState.IsValid)
            {
                _context.Add(meal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: Meals/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meal.FindAsync(id);
            if (meal == null)
            {
                return NotFound();
            }
            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Cuisine,Likes,Comments,YLink")] Meal meal)
        {
            if (id != meal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealExists(meal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: Meals/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

mentionIT/Views/Shared/_Homepage_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.75, maximum-scale=1.10" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>@ViewData["Title"] - MentionIt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>


<body>

    <header style="width: 100%; display: flex; flex-direction: row; justify-content: right;">
        <a class="navbar-brand" asp-area="" asp-controller="Meals" asp-action="Index">
            <img src="~/Images/MentionIT_Logo.png" width="150" height="50" style="margin-top: 10px; position: absolute; left: 20px;" />
        </a>
            <div class="w3-sidebar w3-bar-block w3-animate-right" style="display: none; background-color:orangered;" id="mySidebar">

                <button class="w3-bar-item w3-button"
                        onclick="w3_close()">
                    Close &times;
                </button>

                <ul class="navbar-nav ml-auto">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="w3-bar-item w3-button">
                            <form method="post" asp-action="logout" asp-controller="Accounts">
                                <button type="submit" class="detail-btn" style="width:auto">Logout?</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="w3-bar-item w3-button">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
                        </li>
                        <li class="w3-bar-item w3-button">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="login">Login</a>
                        </li>
                    }

                </ul>

                <div class="search-container">
                    <form method="get" asp-action="Index" class="form-inline" style="float:right;" id="frm">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search" value="@ViewData["Getmeals"]" name="mealSearch" id="search-input">
                        <button class="btn btn-success" type="submit" value="Search" id="search-btn">Search</button>
                    </form>
                </div>

            </div>
            <div>
                <button class="w3-button w3-xxlarge" onclick="w3_open()">&#9776;</button>
            </div>


    </header>

    <div class="topnav" id="myHeader">

        <a asp-action="index">Home</a>
        @if (!signInManager.IsSignedIn(User))
        {
            <a asp-controller="Accounts" asp-action="login">Add Meal</a>
        }
        else
        {
            <a asp-action="ImageAdd">Add Meal</a>
        }
        <a href="#contact">Contact</a>
        <a href="#about">About</a>

    </div>

    <div class="container" style="margin:auto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Category</a></li>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Platforms</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>MentionIt</h3>
                    <p>MentionIt is a College Capstone project that delivers a website for users requiring meal recipes in their area. They can participate in the creation of meal recipes as well as interact with them.</p>                
                </div>
                <div class="col item social">
                    <a href="#!" class="text-danger"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-danger"><i class="fab fa-twitter fa-lg"></i></a>
                    <a href="#!" class="text-danger"><i class="fab fa-google fa-lg"></i></a>
                </div>
            </div>
            <p class="copyright">MentionIt © 2022</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
    }
    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
    }
    
</script>

mentionIT/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - mentionIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Meals" asp-action="Index">
                    <img src="~/Images/MentionIT_Logo.png" width="150" height="50" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="Accounts">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">Logout?</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - mentionIT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mentionIT/Views/Shared/_Login_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - mentionIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>

    <div class="container" style="padding-top:100px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mentionIT/Views/Shared/_Register_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - mentionIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>